Develop
limormek/lim-eat pull request #2
Opened 2017-06-08 08:01 UTC by limormek

2017-06-11 08:00 UTC, yaronyagoda requested changes
Good start
Tell me if things are not clear

2017-06-11 08:00 UTC, yaronyagoda commented on app/models/restaurant.rb
>    validates :rating, numericality: true
Why did u remove the Kosher?

2017-06-11 08:00 UTC, yaronyagoda commented on client/app/bundles/Restaurants/components/Filters/Checkbox.jsx
> +    render() {
A nice convention we have in React is the deconstruction 
const { title, name,  toggle} = this.props;

2017-06-11 08:00 UTC, yaronyagoda commented on client/app/bundles/Restaurants/components/Filters/RangeBar.jsx
> +            <div>
I would add deconstruction here as well.

2017-06-11 08:00 UTC, yaronyagoda commented on config/routes.rb
> +
remove comments

2017-06-11 08:00 UTC, yaronyagoda commented on client/app/bundles/Restaurants/startup/RestaurantsApp.jsx
>  // knowing the locale. See the React on Rails documentation for more info on the railsContext
remove comments

2017-06-11 08:00 UTC, yaronyagoda commented on client/app/bundles/Restaurants/startup/RestaurantsApp.jsx
> +    <Router history={BrowserRouter}>
nice!!!

2017-06-11 08:00 UTC, yaronyagoda commented on client/app/bundles/Restaurants/containers/RestaurantsContainer.jsx
why do u need this class if you are not suing redux?

2017-06-11 08:00 UTC, yaronyagoda commented on client/app/bundles/Restaurants/constants/restaurantsConstants.jsx
>  /* eslint-disable import/prefer-default-export */
what is this comment for?

2017-06-11 08:00 UTC, yaronyagoda commented on client/app/bundles/Restaurants/constants/restaurantsConstants.jsx
>  export const HELLO_WORLD_NAME_UPDATE = 'HELLO_WORLD_NAME_UPDATE';
I like the constants file.
But I think the colors can go to the CSS later., no?

2017-06-11 08:00 UTC, yaronyagoda commented on client/app/bundles/Restaurants/components/RestaurantItem/Restaurant.jsx
> -Restaurants.propTypes = {
why did you remove the prop types?

2017-06-11 08:00 UTC, yaronyagoda commented on client/app/bundles/Restaurants/components/HomePage/Restaurants.jsx
> +        this.state = {filterTenbis: false, filterKosher: false, max_time: 120}
what about filterStars?

2017-06-11 08:00 UTC, yaronyagoda commented on client/app/bundles/Restaurants/components/HomePage/Restaurants.jsx
> +    onToggleCheckbox(e) {
I think maybe 2 methods?

2017-06-11 08:00 UTC, yaronyagoda commented on client/app/bundles/Restaurants/components/HomePage/Restaurants.jsx
> +        //todo change
change :)

2017-06-11 08:00 UTC, yaronyagoda commented on client/app/bundles/Restaurants/components/HomePage/Restaurants.jsx
> +        if (this.state.filterStars) {
I dont think the filtering logic should be in Render
Render should only render...

2017-06-11 08:00 UTC, yaronyagoda commented on client/app/bundles/Restaurants/components/HomePage/Restaurants.jsx
> +                        <Stars title={'Filter by rating:'}
no need for {}

2017-06-11 08:00 UTC, yaronyagoda commented on client/app/bundles/Restaurants/components/HomePage/Restaurants.jsx
> +                               name={'Rating'} count={3} val={0}
not need {}

2017-06-11 08:00 UTC, yaronyagoda commented on client/app/bundles/Restaurants/components/HomePage/Restaurants.jsx
> +                            val={+this.state.max_time}
what is the + here

2017-06-11 08:00 UTC, yaronyagoda commented on client/app/bundles/Restaurants/components/HomePage/Restaurants.jsx
> +    'What\'s your type?', 'Asian', 'Cafe', 'Italian', 'Hamburgers', 'Salads'
why do u need the first one here?

2017-06-11 08:00 UTC, yaronyagoda commented on client/app/bundles/Restaurants/components/Forms/TextInput.jsx
> +    },
why do we need it?

2017-06-11 08:00 UTC, yaronyagoda commented on client/app/bundles/Restaurants/components/Forms/NewRestaurant.jsx
> +                    <button type="submit" disabled={!this.state.canSubmit}>Submit</button>
I think formsy has the enabled disable logic inside
You should not play with it...

2017-06-11 08:00 UTC, yaronyagoda commented on client/app/bundles/Restaurants/components/Forms/FormCheckbox.jsx
> +const WeInput = React.createClass({
Please use class name like the file name

2017-06-11 08:55 UTC, limormek commented on app/models/restaurant.rb
>    validates :rating, numericality: true
Instead I added in the migration null: false (otherwise it forced me to write kosher: true in the seeds)

2017-06-11 09:15 UTC, limormek commented on client/app/bundles/Restaurants/constants/restaurantsConstants.jsx
>  /* eslint-disable import/prefer-default-export */
removed it

2017-06-15 07:22 UTC, yaronyagoda approved these changes
Just minor stuff, looks great!!!!

2017-06-15 07:22 UTC, yaronyagoda commented on client/app/bundles/Restaurants/components/GoogleApiComponent/MyPlace.jsx
>              </div>
Nice!!!

2017-06-15 07:22 UTC, yaronyagoda commented on client/app/bundles/Restaurants/components/HomePage/Restaurants.jsx
>                  </Link>
minor - spacing

2017-06-15 07:22 UTC, yaronyagoda commented on client/app/bundles/Restaurants/components/RestaurantItem/Restaurant.jsx
> +    if(cuisine === 'Fish and Chips') {
Think about adding a switch here.

2017-06-15 07:31 UTC, limormek commented on client/app/bundles/Restaurants/components/RestaurantItem/Restaurant.jsx
> +    if(cuisine === 'Fish and Chips') {
done

2017-06-15 07:58 UTC, merged